-- Content briefs generated by scripts/brief-generator.ts
-- Consumed by scripts/content-generator.ts to produce richer, longer content
create table if not exists briefs (
  id                     uuid primary key default gen_random_uuid(),
  page_slug              text not null unique,
  keyword                text not null,
  target_word_count      int,
  competitor_word_counts jsonb,   -- {"url": wordCount, ...}
  required_subtopics     text[] not null default '{}',
  required_paa_answers   text[] not null default '{}',
  competitor_weaknesses  text[] not null default '{}',
  search_volume          int,
  keyword_difficulty     int,
  generated_at           timestamptz not null default now()
);

create index if not exists briefs_page_slug_idx    on briefs (page_slug);
create index if not exists briefs_generated_at_idx on briefs (generated_at desc);
